set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_VERSION "Generic")

set(CMAKE_SYSTEM "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_VERSION}")

set(TRIPLE aarch64-none-elf)

set(CMAKE_C_COMPILER aarch64-none-elf-gcc)
set(CMAKE_C_COMPILER_TARGET ${TRIPLE})
set(CMAKE_CXX_COMPILER aarch64-none-elf-g++)
set(CMAKE_CXX_COMPILER_TARGET ${TRIPLE})
set(CMAKE_ASM_COMPILER aarch64-none-elf-gcc)
set(CMAKE_ASM_COMPILER_TARGET ${TRIPLE})

set(CMAKE_NM aarch64-none-elf-nm CACHE PATH "The nm program" FORCE)

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -nostdlib")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
